Repository boostcampwm2023/web14-gomterview, pull requests merged in 2023-12, with the labels that each got.

#136 [NDD-271] 질문 리스트 페이지 완성 (그리드와 버튼)
  FE/src/AppRouter.tsx
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/common/ResponsiveMenu/ResponsiveMenu.tsx
  FE/src/components/common/WorkbookCard/WorkbookCard.tsx
  FE/src/components/interviewPage/InterviewFooter/AnswerToggleButton.tsx
  FE/src/components/interviewPage/InterviewFooter/InterviewExitButton.tsx
  FE/src/components/interviewPage/InterviewFooter/NextButton.tsx
  FE/src/components/interviewPage/InterviewFooter/RecordControlButton.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewAnswer.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewQuestion.tsx
  FE/src/components/interviewPage/InterviewMain/Mirror.tsx
  FE/src/components/layout/Header.tsx
  FE/src/components/layout/Header/MenuList.tsx
  FE/src/components/workbookPage/CategoryMenu.tsx
  FE/src/components/workbookPage/GridWorkbookList.tsx
  FE/src/components/workbookPage/RequestLoginModal.tsx
  FE/src/components/workbookPage/Workbook.tsx
  FE/src/components/workbookPage/WorkbookList.tsx
  FE/src/components/workbookPage/WorkbookPageLayout.tsx
  FE/src/components/workbookPage/WorkbookPlusButton.tsx
  FE/src/components/workbookPage/index.tsx
  FE/src/constants/path.ts
  FE/src/constants/queryKey.ts
  FE/src/hooks/apis/queries/useWorkbookListQuery.ts
  FE/src/mocks/handlers/workbook.ts
  FE/src/page/workbookPage/index.tsx
  FE/src/types/workbook.ts
Labels: FE, feature

#139 [NDD-297] QuestionSelectionBox 높이 높이기 (0.3h/1h)
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/index.ts
  FE/src/components/workbookPage/WorkbookPlusButton.tsx
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
Labels: enhancement, FE, feature

#141 [NDD-253]: BE docker pull needs 수정
  .github/workflows/be-cd-dev.yml
Labels: BE, chore

#143 [NDD-316]: CD 찐최종 (0.1h / 1h)
  .github/workflows/be-cd-dev.yml
Labels: BE, bug

#144 Hotfix: 1차 QA설정안 해결
  FE/src/apis/video.ts
  FE/src/hooks/useUploadToIdrive.ts
  FE/src/page/interviewWorkbookDetailPage/index.tsx
  FE/src/types/video.ts
Labels: FE, bug

#148 [NDD-332]: 게시물 수정시에 공개여부 설정 기능 추가 && 조회시 공개여부를 통한 필터링 추가 (1h / 1h)
  BE/src/answer/service/answer.service.spec.ts
  BE/src/question/dto/questionResponse.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/controller/workbook.controller.ts
  BE/src/workbook/dto/createWorkbookRequest.ts
  BE/src/workbook/dto/updateWorkbookRequest.ts
  BE/src/workbook/dto/workbookResponse.ts
  BE/src/workbook/entity/workbook.ts
  BE/src/workbook/fixture/workbook.fixture.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
Labels: enhancement, BE, test, refactor

#151 [NDD-322]: Question 엔드포인트의 예외 HttpCustomException으로 수정 (0.5h / 1h)
  BE/src/question/exception/question.exception.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/token/exception/token.exception.ts
  BE/src/workbook/exception/workbook.exception.ts
Labels: enhancement, BE

#152 [NDD-233]: Pre-Signed URL 발급 API AWS SDK v3로 마이그레이션 (4h / 2h)
  BE/package-lock.json
  BE/package.json
  BE/src/config/idrive.config.ts
  BE/src/util/idrive.util.ts
  BE/src/video/service/video.service.spec.ts
  BE/src/video/service/video.service.ts
Labels: enhancement, BE, chore, test

#154 [NDD-298]: 비디오, 회원 API 에러 케이스 Swagger 작성 (1h / 1h)
  BE/src/constant/constant.ts
  BE/src/member/controller/member.controller.ts
  BE/src/member/exception/member.exception.ts
  BE/src/member/service/member.service.ts
  BE/src/token/exception/token.exception.ts
  BE/src/token/service/token.service.ts
  BE/src/util/exception.util.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/exception/video.exception.ts
Labels: BE, feature, documentation

#155 [NDD-323]: 스웨거 예외 문서처리 && Answer와 Auth API에 대한 에러코드 추가 && delete /question에서 Param수정 (1h / 1h)
  BE/src/answer/controller/answer.controller.ts
  BE/src/answer/exception/answer.exception.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/auth/service/auth.service.ts
  BE/src/member/controller/member.controller.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/exception/question.exception.ts
  BE/src/token/exception/token.exception.ts
  BE/src/workbook/controller/workbook.controller.ts
Labels: enhancement, BE, documentation

#147 [NDD-335] 문제집 페이지에서 All 탭이 없는 이슈 해결 (0.5h / 0.5h)
  FE/src/apis/workbook.ts
  FE/src/components/workbookPage/CategoryMenu.tsx
  FE/src/components/workbookPage/WorkbookList.tsx
  FE/src/constants/api.ts
  FE/src/constants/queryKey.ts
  FE/src/hooks/apis/queries/useWorkbookListQuery.ts
  FE/src/mocks/handlers/workbook.ts
  FE/src/page/workbookPage/index.tsx
Labels: FE, bug

#138 [NDD-258] useModal 훅 추가 (8h/8h)
  FE/src/App.tsx
  FE/src/atoms/modal.ts
  FE/src/hooks/useModal.ts
  FE/src/modalProvider.tsx
Labels: FE, feature

#153 [NDD-276] 면접 세트 삭제, 면접 세트에서 문제 삭제 기능 구현 (6h/2h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/apis/question.ts
  FE/src/components/common/QuestionAccordion/QuestionAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBoxAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelHeader.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookEditModeDialog.tsx
  FE/src/components/foundation/Menu/Menu.tsx
  FE/src/components/foundation/Menu/MenuItem.tsx
  FE/src/components/foundation/Tabs/index.tsx
  FE/src/components/foundation/index.ts
  FE/src/components/myPage/MyPageTabs.tsx
  FE/src/components/workbookPage/CategoryMenu.tsx
  FE/src/hooks/apis/mutations/useDeleteQuestionMutation.tsx
  FE/src/hooks/apis/mutations/useWorkbookDeleteMutation.ts
  FE/src/hooks/useOutsideClick.ts
  FE/src/hooks/useUserInfo.ts
Labels: FE, feature

#157 [NDD-324]: Workbook API에 대한 불필요한 쿼리문을 위한 최적화 && 인덱스 등록 (1h / 1h)
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/controller/workbook.controller.ts
  BE/src/workbook/entity/workbook.ts
  BE/src/workbook/fixture/workbook.fixture.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
Labels: enhancement, BE, refactor

#159 [NDD-337]: 면접용 닉네임 반환 API Controller 테스트 (1h / 1h)
  BE/src/member/controller/member.controller.spec.ts
  BE/src/member/dto/memberNicknameResponse.ts
  BE/src/member/exception/member.exception.ts
  BE/src/member/repository/member.repository.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/exception/video.exception.ts
Labels: BE, test

#156 [NDD-313] tooltip 컴포넌트 생성 (1h/2h)
  FE/src/components/foundation/Tooltip/Tooltip.styles.ts
  FE/src/components/foundation/Tooltip/Tooltip.tsx
  FE/src/components/foundation/index.ts
  FE/src/styles/_colors.ts
Labels: FE, feature

#160 [NDD-339]: Member Service API 테스트 (1h / 1h)
  BE/src/member/controller/member.controller.spec.ts
  BE/src/member/service/member.service.spec.ts
Labels: BE, test

#162 [NDD-326]: Question API 리포지토리 로직 수정 && 인덱싱 확인 (1h / 1h)
  BE/src/question/repository/question.repository.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
Labels: enhancement, BE, refactor

#165 [NDD-330]: 테스트 커버리지 측정 && 누락된 테스트 전체적으로 추가 (2h / 1h)
  BE/package.json
  BE/src/answer/dto/answerListResponse.ts
  BE/src/answer/entity/answer.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/app.service.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/categoryListResponse.ts
  BE/src/category/dto/createCategoryRequest.ts
  BE/src/category/entity/category.ts
  BE/src/category/exception/category.exception.ts
  BE/src/category/fixture/category.fixture.ts
  BE/src/category/repository/category.repository.ts
  BE/src/category/service/category.service.spec.ts
  BE/src/member/entity/member.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/dto/questionResponseList.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/video/dto/videoListResponse.ts
  BE/src/video/service/video.service.spec.ts
  BE/src/video/service/video.service.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
Labels: enhancement, BE, test

#166 [NDD-331]: 비디오/회원 API 쿼리 최적화 (3h / 3h)
  BE/src/member/repository/member.repository.ts
  BE/src/video/entity/video.ts
  BE/src/video/repository/video.repository.ts
Labels: enhancement, BE, feature

#158 [NDD-338] lint-staged추가 (1h/2h)
  .husky/pre-commit
  FE/.githooks/pre-commit
  FE/package-lock.json
  FE/package.json
Labels: FE

#161 [NDD-309] 목소리 사운드 바 기능 추가 (4h/3h)
  FE/src/components/interviewPage/InterviewHeader/InterviewHeader.tsx
  FE/src/components/interviewPage/InterviewHeader/VolumeStatus.tsx
  FE/src/components/interviewPage/InterviewHeader/index.tsx
  FE/src/utils/media.ts
Labels: FE, feature

#168 [NDD-264] 카메라가 꺼짐에 대한 리로딩 기능이 추가 되어야함(3h/3h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/common/Mirror/Mirror.tsx
  FE/src/components/common/index.ts
  FE/src/components/interviewPage/InterviewMain/InterviewMain.tsx
  FE/src/components/interviewPage/InterviewMain/Mirror.tsx
  FE/src/components/interviewPage/InterviewModal/MediaDisconnectedModal.tsx
  FE/src/components/interviewPage/InterviewModal/index.tsx
  FE/src/hooks/pages/Interview/useInterview.ts
  FE/src/hooks/useMedia.tsx
  FE/src/page/interviewPage/index.tsx
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/utils/media.ts
Labels: enhancement, FE, feature

#167 [NDD-307] 비회원도 문제집을 추가, 수정, 삭제. 문제집 내부의 문제도 추가, 삭제하도록 기능 구현 (5h/5h)
  FE/src/apis/workbook.ts
  FE/src/components/common/QuestionSelectionBox/InterviewSetGeneratorModal/InterviewSetGeneratorModal.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionAccordionList.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelHeader.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookAddButton.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookEditModeDialog.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookGeneratorModal/LabelBox.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookGeneratorModal/WorkbookAddForm.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookGeneratorModal/WorkbookCategory.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookGeneratorModal/WorkbookEditForm.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookGeneratorModal/WorkbookGeneratorModal.tsx
  FE/src/components/common/index.ts
  FE/src/components/workbookPage/WorkbookPlusButton.tsx
  FE/src/constants/queryKey.ts
  FE/src/hooks/apis/mutations/useAnswerDefaultMutation.ts
  FE/src/hooks/apis/mutations/useQuestionMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookPatchMutation.ts
  FE/src/hooks/apis/queries/useQuestionWorkbookQuery.ts
  FE/src/hooks/useQuestionAdd.ts
  FE/src/hooks/useWorkbookAdd.ts
  FE/src/hooks/useWorkbookEdit.ts
  FE/src/hooks/useWorkbookQuestionDelete.ts
  FE/src/mocks/handlers/member.ts
  FE/src/mocks/handlers/video.ts
Labels: FE, feature

#163 [NDD-263] 마이페이지에서 권한 없는 영상 조회시 무한로딩 문제 해결 (3h/2h)
  FE/package-lock.json
  FE/package.json
  FE/src/components/common/VideoPlayer/VideoPlayer.tsx
  FE/src/components/common/VideoPlayer/VideoPlayerFrame.tsx
  FE/src/components/common/index.ts
  FE/src/components/foundation/Menu/Menu.tsx
  FE/src/components/interviewVideoPage/InterviewVideoPageLayout.tsx
  FE/src/components/interviewVideoPage/PrivateVideoPlayer.tsx
  FE/src/components/interviewWorkbookDetailPage/InterviewWorkbookDetailPageLayout.tsx
  FE/src/components/landingPage/LandingPageLayout.tsx
  FE/src/components/layout/CenterLayout.tsx
  FE/src/components/layout/Header.tsx
  FE/src/components/layout/Header/Header.tsx
  FE/src/components/layout/Header/Logo.tsx
  FE/src/components/layout/Header/Menu.tsx
  FE/src/components/layout/Header/MenuItem.tsx
  FE/src/components/layout/Header/MenuList.tsx
  FE/src/components/layout/Header/NavigationMenu.tsx
  FE/src/components/layout/Header/Navigations.tsx
  FE/src/components/layout/Header/SideMenu.tsx
  FE/src/components/layout/index.ts
  FE/src/components/workbookPage/WorkbookPageLayout.tsx
  FE/src/hooks/apis/queries/useVideoItemQuery.ts
  FE/src/page/errorPage/index.tsx
  FE/src/page/interviewVideoPage/index.tsx
  FE/src/styles/_colors.ts
Labels: FE, bug

#170 [NDD-341]: 인코딩부터 클라우드 저장후 테이블에 스키마 추가까지 기능 구현 (3h / 3h)
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/util/encoder.util.ts
  BE/src/util/util.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/dto/uploadVideoRequest.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature

#172 [NDD-334]: accessToken, refreshToken을 RDB가 아닌 Redis에 저장하도록 변경 (2h / 3h)
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/app.module.ts
  BE/src/auth/auth.module.ts
  BE/src/constant/constant.ts
  BE/src/member/controller/member.controller.spec.ts
  BE/src/member/service/member.service.spec.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/token/controller/token.controller.ts
  BE/src/token/entity/token.ts
  BE/src/token/repository/token.repository.ts
  BE/src/token/service/token.service.ts
  BE/src/token/token.module.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/service/video.service.spec.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
Labels: enhancement, BE, feature, test

#176 [NDD-347]: accessToken strategy를 사용하는 경우 만료된 토큰에 대한 확인이 불가능한 문제 해결 (3h / 2h)
  BE/src/answer/answer.module.ts
  BE/src/answer/controller/answer.controller.ts
  BE/src/auth/controller/auth.controller.ts
  BE/src/member/controller/member.controller.ts
  BE/src/question/controller/question.controller.ts
  BE/src/token/guard/token.hard.guard.ts
  BE/src/token/service/token.service.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/video.module.ts
  BE/src/workbook/controller/workbook.controller.ts
Labels: enhancement, BE, feature, bug

#171 [NDD-312] Toast 개발 완료 (10h / 8h)
  FE/src/App.tsx
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/foundation/Toast/Toast.styles.ts
  FE/src/components/foundation/Toast/ToastContainer.tsx
  FE/src/components/foundation/Toast/ToastItem.tsx
  FE/src/components/foundation/Toast/collapseToast.ts
  FE/src/components/foundation/Toast/eventManger.ts
  FE/src/components/foundation/Toast/toast.ts
  FE/src/components/foundation/Toast/type.ts
  FE/src/components/foundation/Toast/useToastContainer.ts
  FE/src/styles/_colors.ts
Labels: FE, feature

#177 [NDD-308] 문제집에서 문제 선택해서 바로 면접 연습을 시작할 수 있는 기능 개발하기 (5h / 3h)
  FE/src/AppRouter.tsx
  FE/src/atoms/interviewSetting.ts
  FE/src/components/WorkbookDetailPage/AddWorkbookListModal.tsx
  FE/src/components/WorkbookDetailPage/NewWorkbookListButton.tsx
  FE/src/components/WorkbookDetailPage/StartWithSelectedQuestionModal.tsx
  FE/src/components/WorkbookDetailPage/WorkbookDetailPageLayout.tsx
  FE/src/components/WorkbookDetailPage/index.ts
  FE/src/components/interviewWorkbookDetailPage/index.ts
  FE/src/constants/path.ts
  FE/src/page/WorkbookDetailPage/index.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#180 fix: reissue에 달려있는 guard로 인해 사용하지 못하는 오류 해결
  BE/src/auth/controller/auth.controller.ts
Labels: BE, bug

#187 [NDD-354] 어딜보시는거죠 그건 토스트의 잔상입니다만 해결 완료 (0.1h / 1h)
  FE/src/components/foundation/Toast/ToastItem.tsx
Labels: FE, bug

#188 Be/hotfix
  .github/workflows/be-cd-main.yml
  BE/Dockerfile
  BE/src/auth/controller/auth.controller.ts
  BE/src/category/repository/category.repository.ts
  BE/src/constant/constant.ts
  BE/src/member/repository/member.repository.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
Labels: enhancement, BE, bug, documentation, test

#186 [NDD-350] QuestionSelectionBox에서 사이드바 반응형 대응 (1.5 / 2h)
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.styles.ts
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabList.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelHeader.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/common/QuestionSelectionBox/WorkbookEditModeDialog.tsx
  FE/src/components/foundation/Button/Button.tsx
  FE/src/components/foundation/Menu/MenuItem.tsx
  FE/src/hooks/useBreakPoint.ts
  FE/src/index.tsx
  FE/src/styles/_breakpoints.ts
  README.md
Labels: enhancement, FE

#189 [NDD-311] useModal 오류 해결 및 hook 적용하기 (4h/2h)
  FE/src/App.tsx
  FE/src/AppRouter.tsx
  FE/src/apis/member.ts
  FE/src/components/WorkbookDetailPage/AddWorkbookListModal.tsx
  FE/src/components/WorkbookDetailPage/StartWithSelectedQuestionModal.tsx
  FE/src/components/common/QuestionAccordion/QuestionAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/AnswerSelectionModal/AnswerSelectionModal.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/myPage/DeleteCheckModal.tsx
  FE/src/components/myPage/TabPanel/VideoListTabPanel.tsx
  FE/src/components/workbookPage/RequestLoginModal.tsx
  FE/src/components/workbookPage/WorkbookPlusButton.tsx
  FE/src/hooks/useMedia.tsx
  FE/src/hooks/useModal.ts
  FE/src/mocks/handlers/serverError/video.ts
  FE/src/page/WorkbookDetailPage/index.tsx
  FE/src/page/interviewSettingPage/RecordSettingPage.tsx
  FE/src/utils/media.ts
Labels: FE, bug

#192 [NDD-358]: 클라이언트 측의 비디오 인코딩 작업에 맞게 API 수정 (0.1h / 1h)
  BE/src/video/service/video.service.spec.ts
  BE/src/video/service/video.service.ts
Labels: enhancement, BE, feature

#194 [NDD-367] 에러처리 계층 구조 완료(1h/2h)
  FE/src/APIErrorBoundary.tsx
  FE/src/apis/axios.ts
  FE/src/components/common/StartButton/StartButton.tsx
  FE/src/routes/interviewVideoPublicLoader.ts
Labels: enhancement, FE

#191 [NDD-364] 문제 선택 페이지 헤더추가, 버튼 하단고정, 토스트 잔상 이슈 해결 (2h)
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.styles.ts
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/foundation/StepPages/Step.tsx
  FE/src/components/foundation/StepPages/index.tsx
  FE/src/components/foundation/Toast/ToastContainer.tsx
  FE/src/components/foundation/Toast/ToastItem.tsx
  FE/src/components/interviewSettingPage/Description.tsx
  FE/src/components/interviewSettingPage/InterviewSettingContentLayout.tsx
  FE/src/components/interviewSettingPage/InterviewSettingPageLayout.tsx
  FE/src/components/interviewSettingPage/RecordPage/RecordRadio.tsx
  FE/src/components/interviewSettingPage/interviewSettingFooter.tsx
  FE/src/components/layout/Header/NavigationMenu.tsx
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
  FE/src/page/interviewSettingPage/RecordSettingPage.tsx
  FE/src/page/interviewSettingPage/ServiceTermsPage.tsx
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: enhancement, FE

#195 [NDD-361] 🎉 클라이언트 측에서 webm to mp4 인코딩 구현 🎉 (8h/8h)
  FE/package-lock.json
  FE/package.json
  FE/src/hooks/pages/Interview/useInterview.ts
  FE/src/hooks/useUploadToIdrive.ts
  FE/src/utils/media.ts
  FE/src/utils/record.ts
  FE/webpack.config.js
Labels: FE, feature

#197 [NDD-355] media stream을 전역적으로 관리하기 (3h/2h)
  FE/src/AppRouter.tsx
  FE/src/atoms/media.ts
  FE/src/components/common/Mirror/Mirror.tsx
  FE/src/components/interviewPage/InterviewHeader/VolumeStatus.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewMain.tsx
  FE/src/hooks/atoms/useInterviewSettings.ts
  FE/src/hooks/pages/Interview/useInterview.ts
  FE/src/hooks/useMedia.tsx
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/page/mediaStreamPage/index.tsx
  FE/src/page/myPage/index.tsx
Labels: enhancement, FE

#199 [NDD-363] 문제집이 하나도 없을 때 생성 유도, QuestionSelectionBox 에서 면접세트 보러가기 페이지 유도(1.5h / 2h)
  FE/src/assets/images/blank-bear.png
  FE/src/components/common/QuestionSelectionBox/NoticeDialog/NoticeDialog.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelBlank.tsx
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
Labels: enhancement, FE

#198 [NDD-369] Modal 레이아웃에서 transtion 적용 (0.5h/0.5h)
  FE/src/components/foundation/Modal/ModalLayout.tsx
Labels: FE, feature

#196 [NDD-368]: 해시로 비디오 조회 시 다른 비디오가 조회되는 문제 해결 & 테스트를 위한 ioredis-mock 사용 (6h / 4h)
  .github/workflows/backend_ci_tool.yml
  .github/workflows/be-cd-dev.yml
  BE/package-lock.json
  BE/package.json
  BE/src/util/idrive.util.ts
  BE/src/util/redis.util.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/dto/uploadVideoRequest.ts
  BE/src/video/exception/video.exception.ts
  BE/src/video/service/video.service.spec.ts
  BE/src/video/service/video.service.ts
Labels: enhancement, BE, bug, chore, test

#193 [NDD-342]: 비즈니스로직 트랜잭션화 && DB서버와 메인 서버에 관한 헬스체크 기능 구현 (5h / 2h)
  BE/package-lock.json
  BE/package.json
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/app.module.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/service/category.service.spec.ts
  BE/src/category/service/category.service.ts
  BE/src/config/typeorm.config.ts
  BE/src/health/health.module.ts
  BE/src/health/health.scheduler.ts
  BE/src/main.ts
  BE/src/member/controller/member.controller.spec.ts
  BE/src/member/service/member.service.spec.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/util/test.util.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/service/video.service.spec.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
Labels: enhancement, BE, feature

#202 [NDD-371] 토스트 업데이트 함수 추가, 영상 인코딩 과정 표시 (5h/5h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/foundation/Toast/ToastContainer.tsx
  FE/src/components/foundation/Toast/ToastItem/ToastItem.tsx
  FE/src/components/foundation/Toast/ToastItem/ToastToggleButton.tsx
  FE/src/components/foundation/Toast/constants.ts
  FE/src/components/foundation/Toast/styles/Toast.styles.ts
  FE/src/components/foundation/Toast/styles/ToastAnimation.styles.ts
  FE/src/components/foundation/Toast/toast.ts
  FE/src/components/foundation/Toast/type.ts
  FE/src/components/foundation/Toast/useToastContainer.ts
  FE/src/utils/record.ts
  FE/src/utils/userAgent.ts
Labels: enhancement, FE, bug

#203 [NDD-357]: 문제집 정렬 로직 수정 && 버그픽스 (1h / 1h)
  BE/src/auth/controller/auth.controller.ts
  BE/src/config/typeorm.config.ts
  BE/src/constant/constant.ts
  BE/src/workbook/repository/workbook.repository.ts
Labels: enhancement, BE, bug, refactor

#179 [NDD-348]: AccessToken이 계속해서 Redis에 남아있는 경우 해결 (5h / 2h)
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/auth/service/auth.service.ts
  BE/src/constant/constant.ts
  BE/src/member/repository/member.repository.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/token/service/token.service.ts
  BE/src/util/redis.util.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/fixture/workbook.fixture.ts
Labels: enhancement, BE, feature, test

#205 [NDD-374]: 리드미에 블로그 문서 추가 (0.1h / 0.1h)
  BE/src/main.ts
  README.md
Labels: documentation
