Repository boostcampwm2023/web14-gomterview, pull requests merged in 2023-11, with the labels that each got.

#4 [NDD-56]: release drafter 설정 추가 (1h/1h)
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: FE, chore

#9 [NDD-58] 테마 시스템 정의 (3h/3h)
  FE/src/App.tsx
  FE/src/styles/_colors.ts
  FE/src/styles/_global.ts
  FE/src/styles/_typography.ts
  FE/src/styles/theme.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, feature

#10 [NDD-76] 테마 시스템에 그림자 추가 (0.3 / 1h)
  FE/src/styles/_shadow.ts
  FE/src/styles/theme.ts
Labels: FE

#11 [NDD-75] foundation 컴포넌트 디자인 구현 (1h/1h)
  FE/src/components/Avatar/Avatar.tsx
  FE/src/components/Box/Box.tsx
  FE/src/components/Button/Button.styles.ts
  FE/src/components/Button/Button.tsx
  FE/src/components/InputArea/InputArea.tsx
  FE/src/styles/_colors.ts
  FE/src/types/utils.ts
Labels: FE, feature

#12 [NDD-57] MSW로 서버 mocking하기 (5h/5h)
  FE/package-lock.json
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/constants/api.ts
  FE/src/index.tsx
  FE/src/mocks/browser.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/handlers/answer.ts
  FE/src/mocks/handlers/auth.ts
  FE/src/mocks/handlers/member.ts
  FE/src/mocks/handlers/question.ts
  FE/src/mocks/handlers/video.ts
  FE/webpack.config.js
Labels: FE

#14 [NDD-29]: QuestionItem 컴포넌트 구현, 이에 필요한 foundation 컴포넌트 구현 (6h / 5h)
  FE/src/components/common/QuestionItem/QuestionItem.styles.ts
  FE/src/components/common/QuestionItem/QuestionItem.tsx
  FE/src/components/foundation/Accordion/Accordion.tsx
  FE/src/components/foundation/Accordion/AccordionDetails.tsx
  FE/src/components/foundation/Accordion/AccordionSummary.tsx
  FE/src/components/foundation/Accordion/index.ts
  FE/src/components/foundation/Avatar/Avatar.tsx
  FE/src/components/foundation/Box/Box.tsx
  FE/src/components/foundation/Button/Button.styles.ts
  FE/src/components/foundation/Button/Button.tsx
  FE/src/components/foundation/InputArea/InputArea.tsx
  FE/src/components/foundation/LeadingDot/LeadingDot.tsx
  FE/src/components/foundation/Typography/Typography.tsx
Labels: FE, feature

#20 [NDD-78] PR 템플릿 및 PR티켓 자동으로 할당 (0.5h/1h)
  .github/CODEOWNERS
  .github/pr-badge.yml
  .github/pull_request_template.md
Labels: FE

#21 [NDD-79]: BE 재사용성 있는 코드 분리 && 활용성 확장 (1h / 1h)
  BE/src/util/swagger.util.ts
Labels: BE, feature

#19 [NDD-61]: createBrowserRouter를 통한 Router기능 추가 (8h / 3h)
  FE/.eslintrc.json
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/AppRouter.tsx
  FE/src/components/foundation/Typography/Typography.tsx
  FE/src/components/interviewPage/InterViewCamera.tsx
  FE/src/components/interviewPage/InterViewFooter.tsx
  FE/src/components/interviewPage/Layout.tsx
  FE/src/components/interviewPage/interviewHeader.tsx
  FE/src/components/interviewSettingPage/Description.tsx
  FE/src/components/interviewSettingPage/Layout.tsx
  FE/src/components/interviewSettingPage/QustionSelectionBox.tsx
  FE/src/components/interviewSettingPage/RecordMethodBox.tsx
  FE/src/components/interviewSettingPage/SettingProgressBar.tsx
  FE/src/components/interviewSettingPage/VideoSettingBox.tsx
  FE/src/components/interviewVideoPage/Layout.tsx
  FE/src/components/landingPage/Intro.tsx
  FE/src/components/landingPage/Layout.tsx
  FE/src/components/landingPage/SideBackground.tsx
  FE/src/components/layout/Layout.tsx
  FE/src/components/myPage/Header.tsx
  FE/src/components/myPage/Layout.tsx
  FE/src/components/myPage/MyPageHeader.tsx
  FE/src/components/myPage/Profile.tsx
  FE/src/constants/path.ts
  FE/src/page/LandingPage/index.tsx
  FE/src/page/interviewPage/index.tsx
  FE/src/page/interviewSettingPage/index.tsx
  FE/src/page/interviewVideoPage/index.tsx
  FE/src/page/myPage/index.tsx
  FE/webpack.config.js
Labels: FE, feature

#28 [NDD-99] 테스트를 위한 Jest 설정 변경 (1h / 1h)
  BE/package.json
  BE/src/config/typeorm.config.ts
Labels: BE, chore

#27 [NDD-85] 랜딩 페이지 구현, 웹팩 file-loader, svgr 설정 (9h/8h)
  FE/package.json
  FE/src/assets/images/landing-bear.png
  FE/src/assets/images/logo.png
  FE/src/assets/svg/google-logo.svg
  FE/src/components/common/Logo/Logo.tsx
  FE/src/components/common/QuestionItem/QuestionItem.tsx
  FE/src/components/foundation/Button/Button.styles.ts
  FE/src/components/foundation/Typography/Typography.tsx
  FE/src/components/interviewPage/InterviewCamera.tsx
  FE/src/components/interviewPage/InterviewFooter.tsx
  FE/src/components/interviewPage/InterviewPageLayout.tsx
  FE/src/components/interviewSettingPage/InterviewSettingPageLayout.tsx
  FE/src/components/interviewVideoPage/InterviewVideoPageLayout.tsx
  FE/src/components/landingPage/GoogleLoginButton.tsx
  FE/src/components/landingPage/Intro.tsx
  FE/src/components/landingPage/LandingImage.tsx
  FE/src/components/landingPage/LandingPageHeader.tsx
  FE/src/components/landingPage/LandingPageLayout.tsx
  FE/src/components/landingPage/Layout.tsx
  FE/src/components/landingPage/SideBackground.tsx
  FE/src/components/landingPage/StartButton.tsx
  FE/src/components/landingPage/WelcomeBlurb.tsx
  FE/src/components/layout/Layout.tsx
  FE/src/components/myPage/MyPageLayout.tsx
  FE/src/page/LandingPage/index.tsx
  FE/src/page/interviewPage/index.tsx
  FE/src/page/interviewSettingPage/index.tsx
  FE/src/page/interviewVideoPage/index.tsx
  FE/src/page/myPage/index.tsx
  FE/src/styles/_breakpoints.ts
  FE/src/styles/_global.ts
  FE/src/styles/_gradient.ts
  FE/src/styles/_shadow.ts
  FE/src/styles/_typography.ts
  FE/src/styles/theme.ts
  FE/src/types/type.d.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, feature

#25 [NDD-86] 상태관리 라이브러리 추가 (순수 세팅 시간 1h/8h) (상태 관리 고민시간 4h/???)
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/apis/axios.ts
  FE/src/constants/api.ts
Labels: FE

#29 [NDD-103] Member API E2E 테스트 (1h / 1h)
  BE/.eslintrc.js
  BE/src/config/cors.config.ts
  BE/src/main.ts
  BE/src/member/controller/member.controller.spec.ts
  BE/test/test.util.ts
Labels: BE, test

#30 [NDD-87] Interview 페이지 camera 컴포넌트 기능 부여 (7h/8h)
  FE/src/components/interviewPage/InterviewCamera.tsx
Labels: FE, feature

#35 [NDD-126]: Auth API 리팩터링 (2h / 1h)
  BE/src/auth/controller/auth.controller.ts
  BE/src/auth/dto/tokenResponse.ts
  BE/src/auth/strategy/google.strategy.ts
  BE/src/main.ts
  BE/src/token/strategy/access.token.strategy.ts
  BE/src/util/swagger.util.ts
  BE/src/util/token.util.ts
Labels: BE, feature

#36 [NDD-119]: 면접 화면에 나타나는 이름 반환 API 구현 (1h / 1h)
  BE/src/member/controller/member.controller.ts
  BE/src/member/member.module.ts
  BE/src/member/service/member.service.ts
Labels: BE, feature

#37 [NDD-148] modal 컴포넌트 구현하기 (4h/3h)
  FE/src/assets/svg/close.svg
  FE/src/components/foundation/Box/Box.tsx
  FE/src/components/foundation/Modal/ModalContent.tsx
  FE/src/components/foundation/Modal/ModalFooter.tsx
  FE/src/components/foundation/Modal/ModalHeader.tsx
  FE/src/components/foundation/Modal/ModalLayout.tsx
  FE/src/components/foundation/Modal/index.tsx
  FE/src/styles/_colors.ts
  FE/src/styles/_shadow.ts
  FE/src/utils/enhanceChildElement.ts
Labels: FE, feature

#38 [NDD-136] setting 전역 hook 작성 (1h/2h)
  FE/src/atoms/interviewSetting.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE

#43 [NDD-159]: Category 객체, 리포지토리 구현 (1h / 1h)
  BE/src/category/category.module.ts
  BE/src/category/entity/category.ts
  BE/src/category/repository/category.repository.ts
Labels: BE, feature

#47 [NDD-168] Selection Box 컴포넌트 생성 (2h/2h)
  FE/src/components/foundation/SelectionBox/SelectionBox.styles.tsx
  FE/src/components/foundation/SelectionBox/SelectionBox.tsx
  FE/src/styles/_typography.ts
Labels: FE, feature

#48 [NDD-150] 구글 애널리틱스 설정 완료 (0.5h/1h)
  FE/package-lock.json
  FE/package.json
  FE/src/index.tsx
  FE/webpack.config.js
Labels: FE, feature, chore

#39 [NDD-132] video api mocking 추가 (2h / 2h)
  FE/src/constants/api.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/handlers/video.ts
Labels: FE, feature

#44 [NDD-137] 답변 변경하기 Modal 컴포넌트 구현 (5h/5h)
  FE/src/apis/answer.ts
  FE/src/components/foundation/InputArea/InputArea.tsx
  FE/src/components/interviewSettingPage/AnswerSelectionModal/AnswerForm.tsx
  FE/src/components/interviewSettingPage/AnswerSelectionModal/AnswerScript.tsx
  FE/src/components/interviewSettingPage/AnswerSelectionModal/AnswerSelectionModal.tsx
  FE/src/constants/queryKey.ts
  FE/src/hooks/mutations/useQuestionAnswerMutation.ts
  FE/src/hooks/queries/useQuestionAnswerQuery.ts
  FE/src/hooks/useInput.ts
  FE/src/mocks/handlers/answer.ts
  FE/src/styles/_global.ts
  FE/src/types/answer.ts
  FE/src/utils/getAPIResponseData.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, feature

#46 [NDD-127] GET : /video/all API 구현 (1h / 1h)
  BE/src/member/controller/member.controller.ts
  BE/src/util/token.util.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/dto/singleVideoResponse.ts
  BE/src/video/dto/videoListResponse.ts
  BE/src/video/entity/video.ts
  BE/src/video/repository/video.repository.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature

#49 [NDD-160]: 카테고리 추가 기능 구현 (2h / 1h)
  BE/src/app.module.ts
  BE/src/category/category.module.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/categoryResponse.ts
  BE/src/category/dto/createCategoryRequest.ts
  BE/src/category/entity/category.ts
  BE/src/category/exception/category.exception.ts
  BE/src/category/fixture/category.fixture.ts
  BE/src/category/repository/category.repository.ts
  BE/src/category/service/category.service.spec.ts
  BE/src/category/service/category.service.ts
Labels: BE, feature, test

#51 [NDD-169] svg sprite를 통한 Icon 컴포넌트 개발 (4h/ 3h)
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/GlobalSvgProvider.tsx
  FE/src/assets/svg/close.svg
  FE/src/assets/svg/google-logo.svg
  FE/src/components/foundation/Icon/Icon.tsx
  FE/src/components/foundation/Modal/ModalHeader.tsx
  FE/src/components/landingPage/GoogleLoginButton.tsx
  FE/src/types/type.d.ts
  FE/webpack.config.js
Labels: FE, feature

#50 [NDD-167] tabs foundation 컴포넌트 구현 완료 (4h/3h)
  FE/src/components/foundation/SelectionBox/SelectionBox.tsx
  FE/src/components/foundation/Tabs/Tab.tsx
  FE/src/components/foundation/Tabs/TabList.tsx
  FE/src/components/foundation/Tabs/TabPanel.tsx
  FE/src/components/foundation/Tabs/index.tsx
  FE/src/components/myPage/MyPagesTabs.tsx
  FE/src/page/myPage/index.tsx
  FE/src/utils/addChildElementProps.ts
  FE/src/utils/enhanceChildElement.ts
Labels: FE, feature

#52 [NDD-161]: 회원/비회원의 카테고리 조회 기능 구현 && 비즈니스/컨트롤러 단위/통합 테스트 추가(2h/2h)
  BE/src/category/category.module.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/categoryListResponse.ts
  BE/src/category/entity/category.ts
  BE/src/category/fixture/category.fixture.ts
  BE/src/category/repository/category.repository.ts
  BE/src/category/service/category.service.spec.ts
  BE/src/category/service/category.service.ts
  BE/src/question/controller/question.controller.ts
  BE/src/token/service/token.service.ts
  BE/src/token/strategy/access.token.strategy.ts
  BE/src/util/token.util.ts
Labels: BE, feature, test

#53 [NDD-128]: GET : /video/${videoId} 구현 (2h / 1h)
  BE/src/video/controller/video.controller.ts
  BE/src/video/dto/videoDetailResponse.ts
  BE/src/video/dto/videoListResponse.ts
  BE/src/video/exception/video.exception.ts
  BE/src/video/fixture/video.fixture.ts
  BE/src/video/repository/video.repository.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature

#58 [NDD-172]: 로그인 완료 시 마이페이지로 리다이렉트 되도록 구현 (1h / 1h)
  BE/src/auth/controller/auth.controller.ts
  BE/src/video/dto/createVideoRequest.ts
  BE/src/video/entity/video.ts
Labels: BE, feature

#62 [NDD-179]: 파일 저장을 위한 키를 .mp4에서 .webm으로 변경 (0.2h / 1h)
  BE/src/video/service/video.service.ts
Labels: BE, feature

#57 [NDD-135] Interview 페이지 UI 구현
  FE/src/components/interviewPage/InterviewCamera.tsx
  FE/src/components/interviewPage/InterviewFooter.tsx
  FE/src/components/interviewPage/InterviewFooter/AnswerToggleButton.tsx
  FE/src/components/interviewPage/InterviewFooter/InterviewExitButton.tsx
  FE/src/components/interviewPage/InterviewFooter/InterviewFooter.tsx
  FE/src/components/interviewPage/InterviewFooter/NextButton.tsx
  FE/src/components/interviewPage/InterviewFooter/RecordControlButton.tsx
  FE/src/components/interviewPage/InterviewHeader/InterviewHeader.tsx
  FE/src/components/interviewPage/InterviewHeader/IntervieweeName.tsx
  FE/src/components/interviewPage/InterviewHeader/RecordStatus.tsx
  FE/src/components/interviewPage/InterviewHeader/RecordTimer.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewAnswer.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewMain.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewQuestion.tsx
  FE/src/components/interviewPage/InterviewMain/Mirror.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewExitModal.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewFinishModal.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewIntroModal.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewTimeOverModal.tsx
  FE/src/components/interviewPage/InterviewPageLayout.tsx
  FE/src/components/interviewPage/interviewHeader.tsx
  FE/src/page/interviewPage/index.tsx
Labels: FE, feature

#60 [NDD-144] 마이페이지 부분 기능 없이 마크업만 완료 (4h/3h)
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/src/components/common/Logo/Logo.tsx
  FE/src/components/common/VideoItem/VideoItem.tsx
  FE/src/components/foundation/Button/Button.styles.ts
  FE/src/components/foundation/CardCover/CardCover.tsx
  FE/src/components/interviewVideoPage/InterviewVideoPageLayout.tsx
  FE/src/components/interviewVideoPage/VideoPlayer.tsx
  FE/src/components/myPage/Header.tsx
  FE/src/components/myPage/MyPageHeader.tsx
  FE/src/components/myPage/MyPageLayout.tsx
  FE/src/components/myPage/MyPagesTabs.tsx
  FE/src/components/myPage/Profile.tsx
  FE/src/components/myPage/TabPanel/VideoListTabPanel.tsx
  FE/src/components/myPage/Thumbnail.tsx
  FE/src/index.tsx
  FE/src/page/interviewVideoPage/index.tsx
  FE/src/page/myPage/index.tsx
  FE/webpack.config.js
Labels: FE, feature

#63 [NDD-178]: 회원 이름 반환 시 DTO로 반환하도록 변경 (0.3h / 1h)
  BE/src/member/controller/member.controller.ts
  BE/src/member/dto/memberNicknameResponse.ts
  BE/src/member/service/member.service.ts
Labels: BE, feature

#66 [NDD-153]: PATCH : /api/video/{videoId} 구현 (1h / 1h)
  BE/src/video/controller/video.controller.ts
  BE/src/video/dto/videoHashResponse.ts
  BE/src/video/repository/video.repository.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature

#67 [NDD-129]: DELETE : /video/${videoId} 구현 (1h / 1h)
  BE/src/video/controller/video.controller.ts
  BE/src/video/repository/video.repository.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature

#68 [NDD-220]: BE 배포를 위한 최적화 처리 (2h / 2h)
  BE/Dockerfile
  BE/src/auth/controller/auth.controller.ts
Labels: enhancement, BE, documentation

#70 [NDD-225]: 질문 객체, 리포지토리 구현 (1h / 2h)
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/categoriesResponse.ts
  BE/src/question/dto/createQuestionRequest.ts
  BE/src/question/dto/customQuestionRequest.ts
  BE/src/question/dto/questionListResponse.ts
  BE/src/question/dto/singleQuestionResponse.ts
  BE/src/question/entity/question.ts
  BE/src/question/exception/question.exception.ts
  BE/src/question/fixture/question.fixture.ts
  BE/src/question/question.module.ts
  BE/src/question/repository/question.repository.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
Labels: BE, feature

#45 [NDD-130] 구글 로그인 구현하기, router loader를 통해 리다이랙션 처리하기 (10h/3h)
  .gitignore
  FE/package.json
  FE/src/App.tsx
  FE/src/AppRouter.tsx
  FE/src/apis/axios.ts
  FE/src/apis/member.ts
  FE/src/components/landingPage/GoogleLoginButton.tsx
  FE/src/components/landingPage/LandingPageHeader.tsx
  FE/src/components/landingPage/LandingPageLayout.tsx
  FE/src/components/landingPage/StartButton.tsx
  FE/src/constants/api.ts
  FE/src/constants/queryKey.ts
  FE/src/index.tsx
  FE/src/page/LandingPage/index.tsx
  FE/src/routes/invalidPathLoader.ts
  FE/src/routes/myPageLoader.ts
  FE/src/routes/rootLoader.ts
  FE/src/types/user.ts
  FE/tsconfig.json
  FE/webpack.config.js
Labels: FE, feature

#69 [NDD-134] question select box 컴포넌트 구현하기 (8h/5h)
  FE/src/apis/answer.ts
  FE/src/apis/category.ts
  FE/src/apis/question.ts
  FE/src/atoms/interviewSetting.ts
  FE/src/components/foundation/Tabs/Tab.tsx
  FE/src/components/foundation/Tabs/TabList.tsx
  FE/src/components/foundation/Tabs/TabPanel.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionAccordion.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/constants/api.ts
  FE/src/constants/queryKey.ts
  FE/src/hooks/atoms/useSelectQuestions.ts
  FE/src/hooks/queries/useCategoryQuery.ts
  FE/src/hooks/queries/useQuestionCategoryQuery.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/handlers/category.ts
  FE/src/mocks/handlers/question.ts
  FE/src/types/category.ts
  FE/src/types/question.ts
Labels: FE, feature

#71 [NDD-145] video api 관련 react-query hooks 추가 (1h/2h)
  FE/src/apis/video.ts
  FE/src/constants/queryKey.ts
  FE/src/hooks/mutations/video/useAddVideoMutation.ts
  FE/src/hooks/mutations/video/useDeleteVideoMutation.ts
  FE/src/hooks/mutations/video/useGetPreSignedUrlMutation.ts
  FE/src/hooks/mutations/video/useToggleVideoPublicMutation.ts
  FE/src/hooks/queries/video/useVideoHashQuery.ts
  FE/src/hooks/queries/video/useVideoItemQuery.ts
  FE/src/hooks/queries/video/useVideoListQuery.ts
  FE/src/types/video.ts
  FE/src/utils/getAPIResponseData.ts
Labels: FE, feature

#72 [NDD-227]: 질문 추가 기능 구현 (2h / 1h)
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/entity/category.ts
  BE/src/category/exception/category.exception.ts
  BE/src/category/fixture/category.fixture.ts
  BE/src/member/fixture/member.fixture.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/createQuestionRequest.ts
  BE/src/question/dto/questionResponse.ts
  BE/src/question/exception/question.exception.ts
  BE/src/question/question.module.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/question/util/question.util.ts
  BE/src/token/strategy/access.token.strategy.ts
  BE/src/util/token.util.ts
Labels: BE, feature, test

#75 [NDD-183]: Video API Controller 단위 테스트 (3h / 3h)
  BE/src/config/idrive.config.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/dto/createPreSignedUrlRequest.ts
  BE/src/video/dto/createVideoRequest.ts
  BE/src/video/dto/videoHashResponse.ts
  BE/src/video/fixture/video.fixture.ts
Labels: BE, test

#73 [NDD-228]: 카테고리별 질문 조회 기능 구현 (1h / 1h)
  BE/src/app.entity.ts
  BE/src/category/entity/category.ts
  BE/src/category/repository/category.repository.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/questionResponseList.ts
  BE/src/question/exception/question.exception.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/token/strategy/access.token.strategy.ts
Labels: BE, feature, test

#76 [NDD-232] 비디오 ID/HASH로 단건 조회 시 사용자의 닉네임도 포함하도록 API 변경 (1h / 1h)
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/dto/videoDetailResponse.ts
  BE/src/video/exception/video.exception.ts
  BE/src/video/service/video.service.ts
  BE/src/video/video.module.ts
Labels: BE, feature, test

#77 [NDD-190] Interview 페이지에서 Questions 순서에 따른 질문변경을 반영(마지막 질문의 경우 Mypage로 이동하도록 변경) (10h / 8h)
  FE/package-lock.json
  FE/package.json
  FE/src/components/interviewPage/InterviewFooter/InterviewFooter.tsx
  FE/src/components/interviewPage/InterviewFooter/RecordControlButton.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewFinishModal.tsx
  FE/src/components/interviewPage/InterviewModal/RecordStartModal.tsx
  FE/src/hooks/pages/Interview/useInterviewFlow.ts
  FE/src/hooks/pages/Interview/useIsAllSuccess.ts
  FE/src/hooks/pages/Interview/useWindowSize.ts
  FE/src/page/interviewPage/index.tsx
Labels: FE, feature

#74 [NDD-193] question setting page 페이지 흐름 작성 (4h/3h)
  FE/src/AppRouter.tsx
  FE/src/components/common/ProgressStepBar/ProgressStepBar.tsx
  FE/src/components/common/ProgressStepBar/ProgressStepBarItem.tsx
  FE/src/components/foundation/StepPages/Step.tsx
  FE/src/components/foundation/StepPages/index.tsx
  FE/src/components/interviewSettingPage/QustionSelectionBox.tsx
  FE/src/components/interviewSettingPage/RecordMethodBox.tsx
  FE/src/components/interviewSettingPage/VideoSettingBox.tsx
  FE/src/constants/path.ts
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#78 [NDD-229]: 질문 삭제 로직 구현 && 테스트 (2h / 1h)
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/repository/category.repository.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/questionResponse.ts
  BE/src/question/dto/questionResponseList.ts
  BE/src/question/exception/question.exception.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
Labels: BE, feature, test

#79 [NDD-233]: 면접 화면 전용 사용자 이름 조회 시 기업 이름도 Prefix로 추가되도록 API 변경 (0.5h / 1h)
  BE/src/constant/constant.ts
  BE/src/member/service/member.service.ts
Labels: BE, feature

#82 [NDD-113] Answer 객체 구현 및 기존 로직에서 DefaultAnswer를 가지는 부분을 위한 추가 구현 (1h / 1h)
  BE/src/answer/answer.module.ts
  BE/src/answer/entity/answer.ts
  BE/src/answer/repository/answer.repository.ts
  BE/src/app.module.ts
  BE/src/question/dto/questionResponse.ts
  BE/src/question/entity/question.ts
  BE/src/question/question.module.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/util/question.util.ts
Labels: enhancement, BE, feature

#83 [NDD-236]: 비디오 DB에 등록 시 비디오 길이와 썸네일 URL도 저장할 수 있도록 API 변경 (1h / 1h)
  BE/src/constant/constant.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/dto/createVideoRequest.ts
  BE/src/video/dto/singleVideoResponse.ts
  BE/src/video/entity/video.ts
  BE/src/video/fixture/video.fixture.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature

#84 [NDD-141] 녹화 설정 페이지 구현하기 (2h/3h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/atoms/interviewSetting.ts
  FE/src/components/interviewSettingPage/Description.tsx
  FE/src/components/interviewSettingPage/InterviewSettingPageLayout.tsx
  FE/src/components/interviewSettingPage/RecordMethodBox.tsx
  FE/src/components/interviewSettingPage/RecordPage/RecordRadio.tsx
  FE/src/components/interviewSettingPage/SettingProgressBar.tsx
  FE/src/components/layout/Layout.tsx
  FE/src/page/interviewSettingPage/RecordSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#85 [NDD-114]: 문제에 대한 답변 추가 로직 구현 (1h / 1h)
  BE/src/answer/answer.module.ts
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/controller/answer.controller.ts
  BE/src/answer/dto/answerResponse.ts
  BE/src/answer/dto/createAnswerRequest.ts
  BE/src/answer/entity/answer.ts
  BE/src/answer/fixture/answer.fixture.ts
  BE/src/answer/repository/answer.repository.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/question/question.module.ts
  BE/src/util/test.util.ts
Labels: BE, feature, test

#88 [NDD-139] 문제 선택 페이지 생성 (2h/2h)
  FE/src/components/foundation/SelectionBox/SelectionBox.tsx
  FE/src/components/interviewSettingPage/AnswerSelectionModal/AnswerScript.tsx
  FE/src/components/interviewSettingPage/InterviewSettingPageLayout.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/interviewSettingPage/QustionSelectionBox.tsx
  FE/src/components/layout/Layout.tsx
  FE/src/hooks/atoms/useSelectQuestions.ts
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#87 [NDD-146] 마이페이지 화면 api 연결 (1h/1h)
  FE/src/AppRouter.tsx
  FE/src/components/common/VideoPlayer/VideoPlayer.tsx
  FE/src/components/interviewVideoPage/InterviewVideoPageLayout.tsx
  FE/src/components/interviewVideoPublicPage/InterviewVideoPublicPageLayout.tsx
  FE/src/components/myPage/MyPageLayout.tsx
  FE/src/components/myPage/MyPagesTabs.tsx
  FE/src/components/myPage/Profile.tsx
  FE/src/components/myPage/TabPanel/VideoListTabPanel.tsx
  FE/src/components/myPage/VideoItem/VideoItem.tsx
  FE/src/constants/path.ts
Labels: FE, feature

#89 [NDD-115]: 대표답변을 설정하는 기능 구현 (1h / 1h)
  BE/src/answer/answer.module.ts
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/controller/answer.controller.ts
  BE/src/answer/dto/defaultAnswerRequest.ts
  BE/src/answer/exception/answer.exception.ts
  BE/src/answer/fixture/answer.fixture.ts
  BE/src/answer/repository/answer.repository.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/category/exception/category.exception.ts
  BE/src/question/repository/question.repository.ts
  BE/src/token/exception/token.exception.ts
Labels: BE, feature, test

#92 [NDD-241]: 카테고리 리스트 응답 dto 구조 변경 && 테스트 실패 케이스 수정 (2h / 1h)
  BE/src/category/category.module.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/categoryListResponse.ts
  BE/src/category/repository/category.repository.ts
  BE/src/category/service/category.service.spec.ts
  BE/src/category/service/category.service.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/token/service/token.service.ts
Labels: enhancement, BE, test

#91 [NDD-238] 라우터 로더에서 에러 발생 시 리다이랙션 되지 않고 에러 페이지 표시되는 문제 해결 (0.3/1h)
  FE/src/AppRouter.tsx
  FE/src/routes/interviewVideoPublicLoader.ts
  FE/src/routes/myPageLoader.ts
  FE/src/routes/rootLoader.ts
Labels: FE, bug

#93 [NDD-239] 나만의 질문 입력창 구현하기 (3h/3h)
  FE/src/apis/category.ts
  FE/src/apis/question.ts
  FE/src/components/foundation/Toggle/Toggle.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionAccordion.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionAddForm.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/interviewSettingPage/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/hooks/mutations/useQuestionMutation.ts
  FE/src/hooks/useQuestionAdd.ts
  FE/src/hooks/useUserInfo.ts
  FE/src/mocks/handlers/category.ts
  FE/src/mocks/handlers/question.ts
  FE/src/types/category.ts
Labels: FE, feature

#95 [NDD-140] 화면 소리연결 페이지 구현 (1h/2h)
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#96 [NDD-147] 마이페이지 영상 삭제 기능 구현 (1h/2h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/foundation/CardCover/CardCover.tsx
  FE/src/components/myPage/DeleteCheckModal.tsx
  FE/src/components/myPage/TabPanel/VideoListTabPanel.tsx
  FE/src/components/myPage/Thumbnail.tsx
  FE/src/hooks/mutations/video/useDeleteVideoMutation.ts
  FE/src/mocks/handlers/video.ts
Labels: FE, feature

#90 [NDD-235]: Redis를 이용한 비디오 URL 해싱 (6h / 5h)
  BE/package-lock.json
  BE/package.json
  BE/src/util/redis.util.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/exception/video.exception.ts
  BE/src/video/service/video.service.ts
Labels: BE, feature, test

#94 [NDD-116, NDD-117]: 질문 단건에 대한 답변 리스트 반환 로직 구현 & 답변 삭제 로직 구현 (1+1h / 1+1h)
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/controller/answer.controller.ts
  BE/src/answer/dto/answerListResponse.ts
  BE/src/answer/entity/answer.ts
  BE/src/answer/exception/answer.exception.ts
  BE/src/answer/fixture/answer.fixture.ts
  BE/src/answer/repository/answer.repository.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/answer/util/answer.util.ts
  BE/src/category/util/category.util.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/dto/questionResponseList.ts
  BE/src/question/fixture/question.fixture.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/question/util/question.util.ts
Labels: BE, feature, test

#98 [NDD-240] settingpage 라우터 처리 (1h/2h)
  FE/src/components/interviewSettingPage/QuestionPage/AnswerSelectionModal/AnswerForm.tsx
  FE/src/components/interviewSettingPage/QuestionPage/AnswerSelectionModal/AnswerScript.tsx
  FE/src/components/interviewSettingPage/QuestionPage/AnswerSelectionModal/AnswerSelectionModal.tsx
  FE/src/components/interviewSettingPage/QuestionPage/QuestionSelectionBox/QuestionAccordion.tsx
  FE/src/components/interviewSettingPage/QuestionPage/QuestionSelectionBox/QuestionAddForm.tsx
  FE/src/components/interviewSettingPage/QuestionPage/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/interviewSettingPage/QuestionPage/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/interviewSettingPage/VideoSettingBox.tsx
  FE/src/hooks/useMedia.ts
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
  FE/src/page/interviewSettingPage/RecordSettingPage.tsx
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#100 feat: atom 상태를 전부 관리하는 hook 생성
  FE/src/hooks/atoms/useInterviewSettings.ts
Labels: FE

#97 [NDD-189] Interview 페이지의 interview 관련 로직을 hooks로 분리 (4h / 3h)
  FE/src/apis/idrive.ts
  FE/src/atoms/interviewSetting.ts
  FE/src/components/interviewPage/InterviewModal/InterviewExitModal.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewFinishModal.tsx
  FE/src/hooks/mutations/video/useGetPreSignedUrlMutation.ts
  FE/src/hooks/pages/Interview/useInterview.ts
  FE/src/hooks/pages/Interview/useIsAllSuccess.ts
  FE/src/hooks/pages/Interview/useTimeTracker.ts
  FE/src/hooks/pages/Interview/useUploadToIdrive.ts
  FE/src/page/interviewPage/index.tsx
  FE/src/utils/record.ts
Labels: FE, feature

#99 [NDD-243] 마이페이지 탭에 질문 선택 박스 연결 (0.5h / 1h)
  FE/src/components/common/QuestionSelectionBox/AnswerSelectionModal/AnswerForm.tsx
  FE/src/components/common/QuestionSelectionBox/AnswerSelectionModal/AnswerScript.tsx
  FE/src/components/common/QuestionSelectionBox/AnswerSelectionModal/AnswerSelectionModal.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionAddForm.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/components/myPage/MyPagesTabs.tsx
  FE/src/components/myPage/TabPanel/QuestionSelectTabPanel.tsx
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
  FE/src/page/myPage/index.tsx
Labels: FE, feature

#102 [NDD-251] sentry 세팅 추가
  FE/package-lock.json
  FE/package.json
  FE/src/index.tsx
Labels: FE

#103 [NDD-246] 동영상 업로드 시나리오 완료, 면접 페이지에서 면접자 이름 불러오기 (1h/1h)
  FE/src/apis/member.ts
  FE/src/components/interviewPage/InterviewHeader/InterviewHeader.tsx
  FE/src/components/interviewPage/InterviewHeader/IntervieweeName.tsx
  FE/src/components/interviewPage/InterviewModal/InterviewFinishModal.tsx
  FE/src/components/myPage/MyPageHeader.tsx
  FE/src/constants/api.ts
  FE/src/hooks/mutations/video/useAddVideoMutation.ts
  FE/src/hooks/pages/Interview/useInterview.ts
  FE/src/hooks/pages/Interview/useUploadToIdrive.ts
  FE/src/hooks/queries/useMemberNameQuery.ts
  FE/src/mocks/handlers/member.ts
  FE/src/page/interviewPage/index.tsx
  FE/src/types/user.ts
  FE/src/types/video.ts
  FE/webpack.config.js
Labels: FE, feature

#104 Hotfix v1.0.0
  FE/src/apis/axios.ts
  FE/src/components/common/ProgressStepBar/ProgressStepBar.tsx
  FE/src/components/common/QuestionSelectionBox/AnswerSelectionModal/AnswerSelectionModal.tsx
  FE/src/components/foundation/Accordion/Accordion.tsx
  FE/src/components/foundation/Modal/ModalLayout.tsx
  FE/src/components/foundation/Typography/Typography.tsx
  FE/src/components/interviewPage/InterviewMain/InterviewAnswer.tsx
  FE/src/components/myPage/Profile.tsx
  FE/src/components/myPage/TabPanel/VideoListTabPanel.tsx
  FE/src/components/myPage/Thumbnail.tsx
  FE/src/constants/api.ts
  FE/src/hooks/useQuestionAdd.ts
  FE/src/index.tsx
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
  FE/src/page/interviewSettingPage/RecordSettingPage.tsx
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, bug

#101 [NDD-249]: CI/CD스크립트 추가 && 프론트랑 dto 구조 매칭 (2h / 2h)
  .github/backend_ci_tool.yml
  .github/workflows/backend_ci_tool.yml
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-cd-main.yml
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/controller/answer.controller.ts
  BE/src/answer/dto/answerResponse.ts
  BE/src/answer/entity/answer.ts
  BE/src/answer/service/answer.service.ts
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/service/auth.service.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/categoryListResponse.ts
  BE/src/category/entity/category.ts
  BE/src/category/service/category.service.ts
  BE/src/config/typeorm.config.ts
  BE/src/member/controller/member.controller.spec.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/createQuestionRequest.ts
  BE/src/question/dto/questionResponse.ts
  BE/src/question/entity/question.ts
  BE/src/token/service/token.service.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/controller/video.controller.ts
  BE/src/video/service/video.service.ts
Labels: enhancement, BE, feature, bug, test

#105 [NDD-253] 도커파일 수정
  .github/workflows/be-cd-dev.yml
  .github/workflows/be-cd-main.yml
Labels: documentation

#106 [NDD-254]: 개발용 토큰 반환 API 구현 (0.5h / 0.5h)
  .github/workflows/be-cd-dev.yml
  BE/src/app.controller.ts
  BE/src/auth/service/auth.service.ts
  BE/src/constant/constant.ts
  BE/src/token/service/token.service.ts
  BE/src/token/token.controller.ts
  BE/src/token/token.module.ts
Labels: BE, feature

#107 [NDD-255]: 해시로 조회 시 originUrl이 null일 때 핸들링이 안 되는 현상 픽스 (1h / 1h)
  BE/src/member/exception/member.exception.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/service/video.service.ts
Labels: BE, bug, test

#109 [NDD-261] question 문제 선택 해제시 다음 버튼 비활성화 되는 버그 해결 (0.1h/1h)
  FE/src/hooks/atoms/useSelectQuestions.ts
Labels: FE, bug

#108 [NDD-242] 🎉경축 DX 개선!! 드디어 골칫덩어리 쿠키를 물리쳤다🎉 (1h/2h)
  .gitignore
  FE/.gitignore
  FE/package.json
  FE/src/components/landingPage/GoogleLoginButton.tsx
  FE/src/index.tsx
  FE/tsconfig.json
  FE/webpack.config.js
Labels: enhancement, FE, feature

#110 [NDD-279]: Workbook 엔티티 추가 및 기존의 Category의 전체적 수정을 위한 테스트 리펙토링 (3h / 1h)
  BE/src/answer/answer.module.ts
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/answer/service/answer.service.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/auth/service/auth.service.ts
  BE/src/category/controller/category.controller.spec.ts
  BE/src/category/service/category.service.spec.ts
  BE/src/constant/constant.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/createQuestionRequest.ts
  BE/src/question/entity/question.ts
  BE/src/question/exception/question.exception.ts
  BE/src/question/fixture/question.fixture.ts
  BE/src/question/question.module.ts
  BE/src/question/repository/question.repository.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/workbook/entity/workbook.ts
  BE/src/workbook/exception/workbook.exception.ts
  BE/src/workbook/fixture/workbook.fixture.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/workbook.module.ts
  BE/src/workbook/workbook.util.ts
Labels: BE, feature, test

#111 [NDD-184]: Video Service 단위 테스트 (4h / 3h)
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/dto/videoDetailResponse.ts
  BE/src/video/fixture/video.fixture.ts
  BE/src/video/service/video.service.spec.ts
  BE/src/video/service/video.service.ts
Labels: BE, test

#114 [NDD-267] checkbox 컴포넌트 생성 (0.5h/1h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/foundation/CheckBox/CheckBox.tsx
  FE/src/components/foundation/index.ts
Labels: FE, feature

#115 [NDD-288] workbook 관련 api MSW, react query 작업 완료(2h/2h)
  FE/src/apis/question.ts
  FE/src/apis/workbook.ts
  FE/src/constants/api.ts
  FE/src/constants/queryKey.ts
  FE/src/hooks/apis/mutations/useQuestionCopyMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookDeleteMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookPatchMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookPostMutation.ts
  FE/src/hooks/apis/queries/useWorkbookListQuery.ts
  FE/src/hooks/apis/queries/useWorkbookQuery.ts
  FE/src/hooks/apis/queries/useWorkbookTitleListQuery.ts
  FE/src/mocks/handlers/category.ts
  FE/src/mocks/handlers/question.ts
  FE/src/mocks/handlers/workbook.ts
  FE/src/types/category.ts
  FE/src/types/question.ts
  FE/src/types/workbook.ts
Labels: FE

#113 [NDD-281]: 문제집 객체를 생성한다 (2h / 1h)
  BE/src/answer/controller/answer.controller.spec.ts
  BE/src/answer/service/answer.service.spec.ts
  BE/src/category/controller/category.controller.ts
  BE/src/category/dto/categoryListResponse.ts
  BE/src/category/entity/category.ts
  BE/src/category/fixture/category.fixture.ts
  BE/src/category/repository/category.repository.ts
  BE/src/category/service/category.service.ts
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/controller/workbook.controller.ts
  BE/src/workbook/dto/createWorkbookRequest.ts
  BE/src/workbook/dto/workbookIdResponse.ts
  BE/src/workbook/entity/workbook.ts
  BE/src/workbook/fixture/workbook.fixture.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
  BE/src/workbook/util/workbook.util.ts
  BE/src/workbook/workbook.module.ts
Labels: BE, feature, test

#120 [NDD-185]: Video API Controller 통합 테스트 (5h / 3h)
  BE/src/member/fixture/member.fixture.ts
  BE/src/question/repository/question.repository.ts
  BE/src/util/redis.util.ts
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/entity/video.ts
  BE/src/video/fixture/video.fixture.ts
  BE/src/video/repository/video.repository.ts
  BE/src/video/service/video.service.spec.ts
Labels: BE, test

#121 [NDD-282]: 문제집에 대한 조회 기능 구현 (3h / 1h)
  BE/src/member/fixture/member.fixture.ts
  BE/src/token/guard/token.soft.guard.ts
  BE/src/token/token.module.ts
  BE/src/util/decorator.util.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/controller/workbook.controller.ts
  BE/src/workbook/dto/workbookResponse.ts
  BE/src/workbook/dto/workbookTitleResponse.ts
  BE/src/workbook/entity/workbook.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
  BE/src/workbook/workbook.module.ts
Labels: enhancement, BE, feature, test

#123 [NDD-284]: 문제집 수정 로직 구현 (2h / 1h)
  BE/src/question/controller/question.controller.spec.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/controller/workbook.controller.ts
  BE/src/workbook/dto/updateWorkbookRequest.ts
  BE/src/workbook/entity/workbook.ts
  BE/src/workbook/fixture/workbook.fixture.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
  BE/src/workbook/util/workbook.util.ts
Labels: BE, feature, test

#122 [NDD-266] 질문리스트 카드 컴포넌트 (common) 개발하기 (1h/1h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/common/WorkbookCard/WorkbookCard.tsx
  FE/src/components/common/index.ts
Labels: FE, feature

#116 [NDD-265] 공용으로 사용할 헤더 작업 필요! (Header의 패딩은 기존의 랜딩을 맞출것) (3h/1h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/common/WorkbookCard/WorkbookCard.tsx
  FE/src/components/common/index.ts
  FE/src/components/landingPage/GoogleLoginButton.tsx
  FE/src/components/landingPage/LandingPageLayout.tsx
  FE/src/components/landingPage/index.ts
  FE/src/components/layout/Header.tsx
  FE/src/components/layout/Header/Menu.tsx
  FE/src/components/layout/Header/MenuItem.tsx
  FE/src/components/layout/Header/MenuList.tsx
  FE/src/components/layout/Header/SideMenu.tsx
  FE/src/components/layout/index.ts
  FE/src/components/workbookPage/CategoryMenu.tsx
  FE/src/hooks/useBreakPoint.ts
  FE/src/styles/_breakpoints.ts
  FE/src/utils/redirectToGoogleLogin.ts
Labels: FE, feature

#119 [NDD-289] QuestionSelectionBox API 명세서 변경에 따른 값 변경 (1h/2h)
  FE/src/atoms/interviewSetting.ts
  FE/src/atoms/modal.ts
  FE/src/components/common/QuestionAccordion/QuestionAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/AnswerSelectionModal/AnswerSelectionModal.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionAddForm.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBox.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionSelectionBoxAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/hooks/atoms/useSelectQuestions.ts
  FE/src/hooks/useQuestionAdd.ts
  FE/src/types/utils.ts
  FE/src/types/workbook.ts
Labels: FE, refactor

#117 [NDD-269] AddworkbookListModal 컴포넌트 생성 (3h/3h)
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/foundation/CheckBox/CheckBox.tsx
  FE/src/components/interviewWorkbookDetailPage/AddWorkbookListModal.tsx
Labels: FE, feature

#118 [NDD-272] InterviewSetForm 컴포넌트 생성 (3h/3h)
  FE/src/components/InterviewSetEditPage/InterviewSetCategory.tsx
  FE/src/components/InterviewSetEditPage/InterviewSetForm.tsx
  FE/src/components/InterviewSetEditPage/LabelBox.tsx
  FE/src/components/foundation/Input/Input.tsx
  FE/src/components/foundation/index.ts
  FE/src/hooks/apis/mutations/useWorkbookPatchMutation.ts
  FE/src/hooks/useDebounce.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/handlers/workbook.ts
  FE/src/types/utils.ts
  FE/src/types/workbook.ts
Labels: FE, feature

#125 [hotfix] merge 과정중 사라진 workbook card 이슈 해결
  FE/src/GlobalSvgProvider.tsx
  FE/src/components/common/WorkbookCard/WorkbookCard.tsx
  FE/src/components/common/index.ts
Labels: FE

#124 [NDD-290]: Video Service 통합 테스트 (3h / 3h)
  BE/src/video/controller/video.controller.spec.ts
  BE/src/video/service/video.service.spec.ts
Labels: BE, test

#127 [NDD-292] react-query 훅에 JSDocs 설명 추가 (0.5h / 1h)
  FE/src/hooks/apis/mutations/useAddVideoMutation.ts
  FE/src/hooks/apis/mutations/useAnswerDefaultMutation.ts
  FE/src/hooks/apis/mutations/useDeleteVideoMutation.ts
  FE/src/hooks/apis/mutations/useGetPreSignedUrlMutation.ts
  FE/src/hooks/apis/mutations/useQuestionAnswerMutation.ts
  FE/src/hooks/apis/mutations/useQuestionCopyMutation.ts
  FE/src/hooks/apis/mutations/useQuestionMutation.ts
  FE/src/hooks/apis/mutations/useToggleVideoPublicMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookDeleteMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookPatchMutation.ts
  FE/src/hooks/apis/mutations/useWorkbookPostMutation.ts
  FE/src/hooks/apis/queries/useCategoryQuery.ts
  FE/src/hooks/apis/queries/useMemberNameQuery.ts
  FE/src/hooks/apis/queries/useQuestionAnswerQuery.ts
  FE/src/hooks/apis/queries/useQuestionCategoryQuery.ts
  FE/src/hooks/apis/queries/useVideoHashQuery.ts
  FE/src/hooks/apis/queries/useVideoItemQuery.ts
  FE/src/hooks/apis/queries/useVideoListQuery.ts
  FE/src/hooks/apis/queries/useWorkbookListQuery.ts
  FE/src/hooks/apis/queries/useWorkbookQuery.ts
  FE/src/hooks/apis/queries/useWorkbookTitleListQuery.ts
Labels: documentation

#126 [NDD-274] 문제집에 새로운 문제를 추가하는 InterviewSetQuestionList 컴포넌트 구현(1.5h/3h)
  FE/src/apis/question.ts
  FE/src/components/InterviewSetEditPage/InterviewSetQuestionList.tsx
  FE/src/components/common/QuestionAccordion/QuestionAccordion.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionAddForm.tsx
  FE/src/components/common/QuestionSelectionBox/QuestionTabPanelItem.tsx
  FE/src/hooks/apis/mutations/useQuestionMutation.ts
  FE/src/hooks/apis/queries/useQuestionWorkbookQuery.ts
  FE/src/hooks/useQuestionAdd.ts
  FE/src/mocks/handlers/question.ts
Labels: FE, feature

#129 [NDD-270] 문제집 세부 정보페이지 개발하기 (4h/5h)
  FE/src/AppRouter.tsx
  FE/src/components/common/QuestionAccordion/QuestionAccordion.tsx
  FE/src/components/interviewWorkbookDetailPage/AddWorkbookListModal.tsx
  FE/src/components/interviewWorkbookDetailPage/InterviewWorkbookDetailPageLayout.tsx
  FE/src/components/interviewWorkbookDetailPage/NewWorkbookListButton.tsx
  FE/src/components/interviewWorkbookDetailPage/index.ts
  FE/src/constants/path.ts
  FE/src/constants/queryKey.ts
  FE/src/hooks/apis/queries/useQuestionWorkbookQuery.ts
  FE/src/page/interviewWorkbookDetailPage/index.tsx
  FE/src/routes/interviewWorkbookDetailLoader.ts
Labels: FE, feature

#132 [NDD-262] 에러 페이지 생성 후 라우터에서 errorElement 정의 (2h/2h)
  FE/src/AppRouter.tsx
  FE/src/assets/images/error-bear.png
  FE/src/components/errorPage/ErrorPageLayout.tsx
  FE/src/components/errorPage/index.ts
  FE/src/page/errorPage/index.tsx
  FE/src/routes/interviewVideoPublicLoader.ts
  FE/src/routes/invalidPathLoader.ts
Labels: enhancement, FE, feature

#131 [NDD-293] 약관 동의 페이지 추가 (0.5h/1h)
  FE/src/atoms/interviewSetting.ts
  FE/src/components/interviewSettingPage/index.ts
  FE/src/components/interviewSettingPage/interviewSettingFooter.tsx
  FE/src/constants/path.ts
  FE/src/page/interviewSettingPage/QuestionSettingPage.tsx
  FE/src/page/interviewSettingPage/RecordSettingPage.tsx
  FE/src/page/interviewSettingPage/ServiceTermsPage.tsx
  FE/src/page/interviewSettingPage/VideoSettingPage.tsx
  FE/src/page/interviewSettingPage/index.tsx
Labels: FE, feature

#133 [NDD-268] 질문 리스트 페이지의 SideMenu 컴포넌트 개발(반응형 포함) (7h/5h)
  FE/src/components/common/ResponsiveMenu/ResponsiveMenu.tsx
  FE/src/components/common/index.ts
  FE/src/components/workbookPage/CategoryMenu.tsx
  FE/src/hooks/useThrottleScroll.ts
Labels: FE, feature

#135 [NDD-294] 새로운 면접 세트 생성하는 모달 만들기 (2h/3h)
  FE/src/components/InterviewSetEditPage/InterviewSetForm.tsx
  FE/src/components/InterviewSetEditPage/InterviewSetQuestionList.tsx
  FE/src/components/common/QuestionSelectionBox/InterviewSetEditModal/InterviewSetCategory.tsx
  FE/src/components/common/QuestionSelectionBox/InterviewSetEditModal/InterviewSetForm.tsx
  FE/src/components/common/QuestionSelectionBox/InterviewSetEditModal/InterviewSetGeneratorModal.tsx
  FE/src/components/common/QuestionSelectionBox/InterviewSetEditModal/LabelBox.tsx
  FE/src/hooks/apis/queries/useWorkbookQuery.ts
  FE/src/styles/_colors.ts
Labels: FE, feature

#128 [NDD-285]: 문제집 삭제 로직 구현 (1h / 1h)
  BE/src/workbook/controller/workbook.controller.spec.ts
  BE/src/workbook/controller/workbook.controller.ts
  BE/src/workbook/repository/workbook.repository.ts
  BE/src/workbook/service/workbook.service.spec.ts
  BE/src/workbook/service/workbook.service.ts
Labels: BE, feature, test

#130 [NDD-287]: 질문 복제 로직 구현 (1h / 1h)
  BE/src/member/fixture/member.fixture.ts
  BE/src/question/controller/question.controller.ts
  BE/src/question/dto/copyQuestionRequest.ts
  BE/src/question/fixture/question.fixture.ts
  BE/src/question/repository/question.repository.ts
  BE/src/question/service/question.service.spec.ts
  BE/src/question/service/question.service.ts
Labels: BE, feature, test
